In [2]:
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from wordcloud import WordCloud
from wordcloud import STOPWORDS
import matplotlib.pyplot as plt 
import pandas as pd
import pandas as pd
import numpy as np
from math import pi
from bokeh.plotting import figure
from bokeh.io import show, output_file, output_notebook, push_notebook
from bokeh.layouts import row, column, gridplot
from bokeh.models import CustomJS, Slider
from bokeh.palettes import Spectral6, Category20c,Category10,Accent,Category20
from bokeh.palettes import Greys256,Inferno256,Magma256,Plasma256,Viridis256,Cividis256,Turbo256,linear_palette,Set3,Pastel1,Spectral5,Spectral6
from bokeh.transform import factor_cmap, cumsum
from bokeh.models.widgets import Paragraph,DataTable, TableColumn
from bokeh.models import ColumnDataSource,HoverTool
import numpy as np
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.layouts import LayoutDOM, Box, Row, Column, GridBox, Spacer, WidgetBox
from wordcloud import WordCloud
from wordcloud import STOPWORDS
import matplotlib.pyplot as plt 
from bokeh.models.widgets import Div
from bokeh.layouts import gridplot

In [13]:
#df= pd.read_csv("C:\\Users\\Milgram\\Anaconda3\\Lib\\site-packages\\bokeh\\server\\static\\df.tsv",delimiter='\t',encoding='utf-8')
df=pd.read_csv('C:\\Users\\Milgram\\Desktop\\POC\\train.tsv',delimiter='\t',encoding='utf-8')

In [14]:
df.head(10)

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2
5,6,1,of escapades demonstrating the adage that what...,2
6,7,1,of,2
7,8,1,escapades demonstrating the adage that what is...,2
8,9,1,escapades,2
9,10,1,demonstrating the adage that what is good for ...,2

In [17]:
import re
import nltk 
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

stop_words=set(stopwords.words('english'))
lemma=WordNetLemmatizer()

def clean_Phrase(phrase_text):
    phrase_text=re.sub(r'http\S+','',phrase_text)                             #removing the url
    phrase_text=re.sub('[^a-zA-Z]','',phrase_text)                            #removing Numbers and punctuatino
    phrase_text=str(phrase_text).lower()                                      #Convert all characters into lowercase
    phrase_text=word_tokenize(phrase_text)                                    #Tokenization
    phrase_text=[item for item in phrase_text if item not in stop_words]      #Removing Stop Words
    phrase_text=[lemma.lemmatize(word=w,pos='v') for w in phrase_text]        #Lemmatization
    phrase_text=[i for i in phrase_text if len(i)>2]                          #Remove the words havig length <=2
    phrase_text=''.join(phrase_text)                                          #Converting list to string
    return phrase_text

df['clean_Phrase']=df['Phrase'].apply(clean_Phrase)
#df1['clean_Phrase']=df1['Phrase'].apply(clean_Phrase)

In [18]:
df.head(10)

,PhraseId,SentenceId,Phrase,Sentiment,clean_Phrase
0,1,1,A series of escapades demonstrating the adage ...,1,aseriesofescapadesdemonstratingtheadagethatwha...
1,2,1,A series of escapades demonstrating the adage ...,2,aseriesofescapadesdemonstratingtheadagethatwha...
2,3,1,A series,2,aseries
3,4,1,A,2,
4,5,1,series,2,series
5,6,1,of escapades demonstrating the adage that what...,2,ofescapadesdemonstratingtheadagethatwhatisgood...
6,7,1,of,2,
7,8,1,escapades demonstrating the adage that what is...,2,escapadesdemonstratingtheadagethatwhatisgoodfo...
8,9,1,escapades,2,escapades
9,10,1,demonstrating the adage that what is good for ...,2,demonstratingtheadagethatwhatisgoodforthegoose

In [21]:
from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models.widgets import Slider, Div


def change_datatable(attr, old, new):
    if slider.value == 0:
        df0=df[(df.Sentiment ==0)]
        df0.sort_values(by=['Phrase'], inplace=True,ascending=False)
        df0.head(10)
        x=df0['clean_Phrase'].value_counts()
        data0 = pd.Series(x).reset_index(name='Count').rename(columns={'index':'clean_Phrase'}) 
        #df1=data.head(15)
        #df0.sort_values(by=['Count'], inplace=True,ascending=False)
        data0.head(10)
        source = ColumnDataSource(data0.head(10))
        columns = [
                    TableColumn(field="clean_Phrase", title='Sentiment0'),
                    TableColumn(field="Count", title='TOP 10')
                    ]
        dt0= DataTable(source=source, columns=columns, width=600, height=400)
        #p7=DataTable.title="TOP 5 Sentiments"
        #show(dt0)
    elif slider.value == 1:
        df1=df[(df.Sentiment ==1)]
        df1.sort_values(by=['Phrase'], inplace=True,ascending=False)
        df1.head(10)
        x=df1['clean_Phrase'].value_counts()
        data1 = pd.Series(x).reset_index(name='Count').rename(columns={'index':'clean_Phrase'}) 
        #df1=data.head(15)
        #df0.sort_values(by=['Count'], inplace=True,ascending=False)
        data1.head(10)
        source = ColumnDataSource(data1.head(10))
        columns = [
                    TableColumn(field="clean_Phrase", title='Sentiment1'),
                    TableColumn(field="Count", title='TOP 10')
                    ]
        dt1= DataTable(source=source, columns=columns, width=600, height=400)
        #p7=DataTable.title="TOP 5 Sentiments"
        #show(dt0)
    elif slider.value == 2:
        df2=df[(df.Sentiment ==2)]
        df2.sort_values(by=['Phrase'], inplace=True,ascending=False)
        df2.head(10)
        x=df2['clean_Phrase'].value_counts()
        data2 = pd.Series(x).reset_index(name='Count').rename(columns={'index':'clean_Phrase'}) 
        #df1=data.head(15)
        #df0.sort_values(by=['Count'], inplace=True,ascending=False)
        data2.head(10)
        source = ColumnDataSource(data2.head(10))
        columns = [
                    TableColumn(field="clean_Phrase", title='Sentiment2'),
                    TableColumn(field="Count", title='TOP 10')
                    ]
        dt2= DataTable(source=source, columns=columns, width=600, height=400)
        #p7=DataTable.title="TOP 5 Sentiments"
        #show(dt0)
    elif slider.value == 3:
        df3=df[(df.Sentiment ==3)]
        df3.sort_values(by=['Phrase'], inplace=True,ascending=False)
        df3.head(10)
        x=df3['clean_Phrase'].value_counts()
        data3 = pd.Series(x).reset_index(name='Count').rename(columns={'index':'clean_Phrase'}) 
        #df1=data.head(15)
        #df0.sort_values(by=['Count'], inplace=True,ascending=False)
        data3.head(10)
        source = ColumnDataSource(data3.head(10))
        columns = [
                    TableColumn(field="clean_Phrase", title='Sentiment3'),
                    TableColumn(field="Count", title='TOP 10')
                    ]
        dt3= DataTable(source=source, columns=columns, width=600, height=400)
        #p7=DataTable.title="TOP 5 Sentiments"
        #show(dt0)
    else:
        df4=df[(df.Sentiment ==4)]
        df4.sort_values(by=['Phrase'], inplace=True,ascending=False)
        df4.head(10)
        x=df4['clean_Phrase'].value_counts()
        data4 = pd.Series(x).reset_index(name='Count').rename(columns={'index':'clean_Phrase'}) 
        #df1=data.head(15)
        #df0.sort_values(by=['Count'], inplace=True,ascending=False)
        data4.head(10)
        source = ColumnDataSource(data4.head(10))
        columns = [
                    TableColumn(field="clean_Phrase", title='Sentiment4'),
                    TableColumn(field="Count", title='TOP 10')
                    ]
        dt4= DataTable(source=source, columns=columns, width=600, height=400)
        #p7=DataTable.title="TOP 5 Sentiments"
        #show(dt0)
slider = Slider(start=0, end=4, value=1, title="datatable number")
slider.on_change('value', change_datatable)
pre=Div(text=""" <div><h3><strong><center> Sentimental Analysis</center></strong><h3></div>""",
        align='center',style={'color':'firebrick','font-size':'25px','font-family':'Helvetica'})
#logo = Div(text="""<img src="static/image/logo.png"  alt="logo">""")

curdoc().add_root(row(pre,slider))
curdoc().title = "DataTable Demo"

In [20]:
        df0=df[(df.Sentiment ==0)]
        df0.sort_values(by=['Phrase'], inplace=True,ascending=False)
        df0.head(10)
        x=df0['clean_Phrase'].value_counts()
        data0 = pd.Series(x).reset_index(name='Count').rename(columns={'index':'clean_Phrase'}) 
        #df1=data.head(15)
        #df0.sort_values(by=['Count'], inplace=True,ascending=False)
        data0.head(10)
        source = ColumnDataSource(data0.head(10))
        columns = [
                    TableColumn(field="clean_Phrase", title='Sentiment0'),
                    TableColumn(field="Count", title='TOP 10')
                    ]
        dt0= DataTable(source=source, columns=columns, width=600, height=400)
        #p7=DataTable.title="TOP 5 Sentiments"
        show(dt0)

C:\Users\Milgram\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy